### ISSUE TITLE
thats my plugin,stop forking our stuff

### ISSUE THREAD

**Issue by matthew4444** [LostTeam/Pets#1]

**Comment by jasonwynn10** [comment]
1. we didn't fork this repo from you
2. github made forking for a reason
3. where is this "our" coming from?

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
our

**Comment by matthew4444** [comment]
u did i made the repo on pmmp devs then lucky forked it then u

**Comment by jasonwynn10** [comment]
but I didn't fork it from you, I got it from lucy

**Comment by jasonwynn10** [comment]
I'm also doubting that you origonally started this project because if [this](https://github.com/matthew4444/Pets/network/members).

**Comment by matthew4444** [comment]
Just look at my name in the contubions

**Comment by jasonwynn10** [comment]
I see, but how did you publish it to lucy's account?

**Comment by matthew4444** [comment]
i didnt

**Comment by matthew4444** [comment]
i foked it they forked after me

**Comment by matthew4444** [comment]
u then did it and i reforkweed

**Comment by jasonwynn10** [comment]
"reforkweed"

**Comment by matthew4444** [comment]
re forked

**Comment by MCUnderground** [comment]
Not needed.

**Comment by jasonwynn10** [comment]
thats fair
