### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Driesboy** [LostTeam/Pets#10]
Fatal error: Cannot use pocketmine\plugin\PluginBase as PluginBase because the name is already in use in /Applications/Genisys/plugins/Pets-Php7/src/Pets/Pets.php on line 10

**Comment by jasonwynn10** [comment]
I don't know php7 yet, so I'll leave the php7 branch for you

**Comment by Driesboy** [comment]
ok thx

**Comment by Driesboy** [comment]
thats so cool thx
