### ISSUE TITLE
Pets don't die

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/Pets#10]
After a precaution I added for the clearing functionality, when a pet is attempted to be killed or cycled, it becomes inactive and spawns the next mob in the cycle

**Comment by GlitchPlayer** [comment]
Yep, Im trying to fix it later.

**Comment by jasonwynn10** [comment]
I know of a way I think

**Comment by GlitchPlayer** [comment]
Maybe you could use the old clear command on old repo?

**Comment by GlitchPlayer** [comment]
My commit should fix this issue

**Comment by jasonwynn10** [comment]
let me finish testing before the issue is closed

**Comment by GlitchPlayer** [comment]
kk

**Comment by GlitchPlayer** [comment]
Done Testing?
