### ISSUE TITLE
I dont get message and i cannot see my pet

### ISSUE THREAD

**Issue by Driesboy** [LostTeam/Pets#12]

**Comment by jasonwynn10** [comment]
keep in mind this isn't a finished project yet

**Comment by Driesboy** [comment]
i think the commands dont work

**Comment by Driesboy** [comment]
can you add me to the LostTeam???

**Comment by jasonwynn10** [comment]
I gave you write permissions

**Comment by Driesboy** [comment]
Ok

Verstuurd vanaf mijn iPad
