### ISSUE TITLE
lowercase "main.php" for class Main results in error on linux

### ISSUE THREAD

**Issue by ToddScott** [LostTeam/Pets#13]
- [x ] This issue isn't related to third party builds of PocketMine
- [ x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ x] This issue matches the contributing guidelines - the link is just above the title field.

On linux the plugin does not load properly because the class Main is in a file that is all lowercase.  Changing the file from main.php to Main.php results in the plugin loading and working properly on linux servers.

Try loading the plugin on a linux based server

## Client information
ubuntu
php7
0.15

**Comment by SalmonGER** [comment]
He's right.
The file is named main.php but the plugin.yml looks for a Main.php
https://github.com/LostTeam/Pets/blob/master/plugin.yml#L2
