### ISSUE TITLE
questions  FROM MATTHEW4444

### ISSUE THREAD

**Issue by matthew4444** [LostTeam/Pets#15]
how long will it take to FINISH THIS PLUGIN FROM MATTHEW4444,and i started this prjoct orgnailly so give me some credit.

**Comment by matthew4444** [comment]
can this help? http://www.planetminecraft.com/forums/entity-player-coordinates-but-t439382.html and scrool down and ull se a tp cmd and can uu make that into plugin code for mob tp?

**Comment by matthew4444** [comment]
or can this help?$player->entity->z + floatval(substr($z, 1)):floatval($z); $player->teleport(new Vector3($x, $y, $z)); return true; } return false; } public function get($name, $alike ...

**Comment by jasonwynn10** [comment]
1. Not for a month
2. at least format your code if your going to ask if it will help
3. What did that link have anything to do with this? that was for PC

**Comment by matthew4444** [comment]
kk
