### ISSUE TITLE
Issue in class to string conversion

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/Pets#3]
I receive an error when I try to run it on my server. It keeps saying it can't convert the class to a string and that the problem is on Line [32](https://github.com/LostTeam/Pets/blob/master/src/LostTeam/main.php#L32) of main.php

It has something to do with
```php
new PetCommand($this, "pets"));
``` 
does anyone have a way to fix this?

**Comment by jasonwynn10** [comment]
the php7 version has no issue with this

**Comment by GlitchPlayer** [comment]
Hm....

**Comment by GlitchPlayer** [comment]
Can you show a pic?

**Comment by jasonwynn10** [comment]
```
[15:53:29] [Server thread/NOTICE]: ClassCastException: "Object of class LostTeam\Main could not be converted to string" (E_RECOVERABLE_ERROR) in "/src/pocketmine/command/Command" at line 62
```
